[profile.default]
solc = "0.8.26"
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
evm_version = "cancun"

[rpc_endpoints]
# Add your Alchemy URL here later for forking, e.g.:
# mainnet = "COPY PASTE YOUR MAINNET URL HERE"
